import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import Banner from '../components/Home/Banner'
import NotVerifiedGrug from '../components/NotVerifiedGrug'
import { RootState } from '../store'
import styles from '../styles/Home.module.css'



const Home: NextPage = () => {
  const wallet  = useSelector((state: RootState) => state.wallet)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />

        {/* { wallet.balance && Number.parseInt(wallet.balance, 10) > 0 ? (
            <h1 className={styles.title}>
              GRUGs LAIR
            </h1>
          ) : (
            <NotVerifiedGrug />
          )
        } */}

      </main>
    </div>
  )
}

export default Home
